config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'admin' => 'admins#home'
  get 'kitchen' => 'cook_rooms#home'
  get 'config_user' => 'admins#setup'
  post 'contact' => 'welcome#contact'
  root 'welcome#home'
  get 'products_by_categorie' => 'products#products_by_categorie'
  get 'add_op' => 'orders#add_item'
  get 'remove_op' => 'orders#remove_item'
  get 'generate_invoice' => 'invoices#generate_invoice'
  get 'dashboard' => 'dashboard#home'
  resources :establishments
  resources :ingredients
  resources :inventarios
  resources :products
  resources :product_ingredients
  resources :orders
  resources :invoices

end

app/views/admins/home.html.erb
<div class="container" id="admin_home" >
	<div class="page-header">
	  <h1>Bienvenido <%= current_user.try(:name) %> <%= current_user.try(:last_name) %> <small><%= current_user.establishment.name if current_user.establishment %></small></h1>
	</div>

	<% if current_user.establishment == nil %>
		<div class="row text-center">
			<%= link_to 'Agregar establecimiento', new_establishment_path, :class => 'btn pos_button_black' %>
		</div>
	<% else %>
		<div class="row">
			<div class="col-md-4 col-md-offset-2">
				<%= link_to ("<div class='thumbnail text-center'><span class='fa-stack fa-4'><i class='fa fa-square fa-stack-2x'></i><i class='fa fa-cutlery fa-stack-1x fa-inverse'></i></span><div class='caption text-center'><p>ORDENES</p></div></div>").html_safe, orders_path %>			
			</div>
			<div class="col-md-4">
				<%= link_to ("<div class='thumbnail text-center'><span class='fa-stack fa-4'><i class='fa fa-square fa-stack-2x'></i><i class='fa fa-files-o fa-stack-1x fa-inverse'></i></span><div class='caption text-center'><p>COCINA</p></div></div>").html_safe, kitchen_path %>				
			</div>
		</div>
	<% end %>
</div>

app/views/admins/setup.html.erb
Aqui se debe renderizar las preferencias de usuario para configurar su cuenta