config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'admin' => 'admins#home'
  get 'kitchen' => 'cook_rooms#home'
  get 'config_user' => 'admins#setup'
  post 'contact' => 'welcome#contact'
  root 'welcome#home'
  get 'products_by_categorie' => 'products#products_by_categorie'
  get 'add_op' => 'orders#add_item'
  get 'remove_op' => 'orders#remove_item'
  get 'generate_invoice' => 'invoices#generate_invoice'
  get 'dashboard' => 'dashboard#home'
  resources :establishments
  resources :ingredients
  resources :inventarios
  resources :products
  resources :product_ingredients
  resources :orders
  resources :invoices

end

app/models/ingredient.rb
# == Schema Information
#
# Table name: ingredients
#
#  id                  :integer          not null, primary key
#  name                :string
#  unit_of_measurement :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class Ingredient < ActiveRecord::Base
	has_many :establishment_ingredients
	has_many :product_ingredients
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
	before_action :authenticate_user!
	def new
		@ingredient = Ingredient.new
	end

	def create
		@ingredient = Ingredient.new(ingredient_params)
		if @ingredient.save
			redirect_to @ingredient
		end
	end

	def show
		@ingredient = Ingredient.find(params[:id])
	end

	def edit
		@ingredient = Ingredient.find(params[:id])
	end

	def update
		@ingredient = Ingredient.find(params[:id])
		if @ingredient.update(ingredient_params)
			redirect_to @ingredient			
		end
	end

	def index
		@ingredients = Ingredient.all
	end

	def destroy
		@ingredient = Ingredient.find(params[:id])
		@ingredient.destroy
		redirect_to ingredients_path
	end

	private
		def ingredient_params
  		params.require(:ingredient).permit(:name, :unit_of_measurement)
		end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<div class="content">
  <%= form_for @ingredient do |f| %>
  	<div class="field form-group">
    	<%= f.label :name %><br>
    	<%= f.text_field :name, :class => "form-control" %>
    </div>
    <div class="field form-group no-padding-bottom">
    	<%= f.label :unidad_de_medida %><br>
    	<%= f.text_field :unit_of_measurement, :class => "form-control" %>
    </div>
    <div class="actions form-group text-center">
      <%= f.submit 'Guardar Ingrediente', :class => 'btn pos_button_blue' %>
    </div>
  <% end %>
</div>

app/views/ingredients/edit.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h2>Editar Ingrediente</h2>
    <%= render "form" %>
  </div>
</div>

app/views/ingredients/index.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<table class="table">
		<tr>
			<th>Name</th>
			<th>Unidad de Medida</th>
		  <th>Editar - Borrar</th>
		</tr>
		<% @ingredients.each do |i| %>
			<tr>
				<td> <%= i.name %> </td>
				<td> <%= i.unit_of_measurement %> </td>
				<td> <%= link_to 'Editar', edit_ingredient_path(i) %> - <%= link_to ingredient_path(i), method: :delete, data: { confirm: 'Are you sure?' } do %><span>Borrar</span><% end %></td>
			</tr>
		<% end %>
	</table>
	<%= link_to 'Agregar ingrediente', new_ingredient_path %>
	</div>
</div>

app/views/ingredients/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h2 class="text-center">NUEVO INGREDIENTE</h2>
    <%= render "form" %>
  </div>
</div>

app/views/ingredients/show.html.erb
<div class="row margin-container">
	<div class="col-md-4 col-md-offset-4 text-center">
		<h2 class="text-center">Nuevo Ingrediente Agregado</h2>
		<div class="container text-left">
			<h4>Nombre: <%= @ingredient.name %></h4>
			<h4>Unidad de medida: <%= @ingredient.unit_of_measurement %></h4>
		</div>
		<%= link_to 'Continuar', admin_path, :class => 'btn btn-warning' %> 
	</div>
</div>