config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'admin' => 'admins#home'
  get 'kitchen' => 'cook_rooms#home'
  get 'config_user' => 'admins#setup'
  post 'contact' => 'welcome#contact'
  root 'welcome#home'
  get 'products_by_categorie' => 'products#products_by_categorie'
  get 'add_op' => 'orders#add_item'
  get 'remove_op' => 'orders#remove_item'
  get 'generate_invoice' => 'invoices#generate_invoice'
  get 'dashboard' => 'dashboard#home'
  resources :establishments
  resources :ingredients
  resources :inventarios
  resources :products
  resources :product_ingredients
  resources :orders
  resources :invoices

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id                  :integer          not null, primary key
#  name                :string
#  precio              :integer
#  establishment_id    :integer
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  categorie_id        :integer
#  avatar_file_name    :string
#  avatar_content_type :string
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#

class Product < ActiveRecord::Base
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  belongs_to :categorie
  belongs_to :establishment
  has_many :product_ingredients, dependent: :destroy
  has_many :order_products
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :authenticate_user!
	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)
		if @product.save
			redirect_to @product
		end
	end

	def show
		@product = Product.find(params[:id])
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])
		if @product.update(product_params)
			redirect_to @product			
		end
	end

	def index
		@products = Product.all
	end

	def products_by_categorie
		categorie_name = params[:categorie]
		@categorie = Categorie.find_by(name: categorie_name)
		@products = Product.where(categorie_id: @categorie.id)
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		redirect_to products_path
	end

	private
		def product_params
  		params.require(:product).permit(:name, :precio, :categorie_id, :establishment_id, :avatar)
		end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="content">
  <%= form_for @product do |f| %>
  	<div class="field form-group">
    	<%= f.label :name %><br>
    	<%= f.text_field :name, :class => "form-control" %>
    </div>
    <div class="field form-group">
    	<%= f.label :precio %><br>
    	<%= f.text_field :precio, :class => "form-control" %>
    </div>
    <div class="field form-group">
      <%= f.label :establishment_id %><br>
      <%= f.collection_select(:establishment_id, Establishment.all, :id, :name, {include_blank: true}, {:class => 'form-control'}) %>
    </div>
    <div class="field form-group">
      <%= f.label :category_id %><br>
      <%= f.collection_select(:categorie_id, Categorie.all, :id, :name, {include_blank: true}, {:class => 'form-control'}) %>
    </div>
    <div class="field">
      <%= f.label :imagen %><br>
      <%= f.file_field :avatar, :class => "upload_avatar" %>
    </div>
    <div class="actions form-group text-center">
      <%= f.submit 'Guardar Producto', :class => 'btn pos_button_blue' %>
    </div>
  <% end %>
</div>

app/views/products/_item.html.erb
<div data-id='<%= product.id%>' data-name='<%= product.name %>' data-image='<%= product.avatar.url %>' class='col-lg-3 col-md-3 col-sm-3 col-xs-3 text-center content categorie_content pick-product'>
	<img src='<%= product.avatar.url(:thumb) %>' alt='<%= product.name %>' class='img-responsive'/>
	<%= product.name %>
</div>

app/views/products/_item_edit.html.erb
<%= link_to add_op_path(:order_id => params[:order_id], :product_id => product.id), remote: true do %>
	<div data-id='<%= product.id%>' data-name='<%= product.name %>' data-image='<%= product.avatar.url %>' class='col-lg-3 col-md-3 col-sm-3 col-xs-3 text-center content categorie_content pick-product'>
		<img src='<%= product.avatar.url(:thumb) %>' alt='<%= product.name %>' class='img-responsive'/>
		<%= product.name %>
	</div>
<% end %>

app/views/products/edit.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h2 class="text-center">EDITAR PRODUCTO</h2>
    <%= render "form" %>
  </div>
</div>

app/views/products/index.html.erb
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<table class="table table-hover table-condensed">
		<tr class="text-center">
			<th>IMAGEN</th>
			<th>NOMBRE</th>
			<th>PRECIO</th>
			<th>CATEGORIA</th>
			<th>ESTABLECIMIENTO</th>
		  <th>OPCIONES</th>
		</tr>
		<% @products.each do |p| %>
			<tr>
				<td class="vert-align"> <%= image_tag p.avatar.url(:thumb) %></td>
				<td class="vert-align"> <%= p.name %></td>
				<td class="vert-align"> <%= number_to_currency(p.precio, :precision => 0) %> </td>
				<td class="vert-align"> <%= Categorie.find(p.categorie_id).name %> </td>
				<td class="vert-align"> <%= p.establishment.name %> </td>
				<td class="vert-align"> <%= link_to edit_product_path(p) do %> Editar <% end %> - <%= link_to product_path(p), method: :delete, data: { confirm: 'Are you sure?' } do %><span>Borrar</span><% end %> - <%= link_to 'Ver Receta', p %></td>
			</tr>
		<% end %>
	</table>
	<div class="row text-center">
		<%= link_to 'Agregar nuevo producto', new_product_path, :class => 'btn pos_button_blue' %>
	</div>
	</div>
</div>

app/views/products/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h2 class="text-center">NUEVO PRODUCTO</h2>
    <%= render "form" %>
  </div>
</div>

app/views/products/products_by_categorie.js.erb
$('#categorie_products').html('');
$('#categorie_products_edit').html('');
<% @products.each do |p| %>
	$('#categorie_products').append("<%= j render partial: 'item', locals: { product: p } %>");
	$('#categorie_products_edit').append("<%= j render partial: 'item_edit', locals: { product: p } %>");
<% end %>

app/views/products/show.html.erb
<div class="row margin-container">
	<div class="col-md-6 col-md-offset-3 text-center">
		<h2 class="text-center">INFORMACION DE PRODUCTO</h2>
			<row class="text-left">
				<%= image_tag @product.avatar.url(:medium) %>
				<div class="content">
					<h4>NOMBRE: <%= @product.name %></h4>
					<h4>PRECIO: <%= number_to_currency(@product.precio, :precision => 0) %></h4>
					<h4>ESTABLECIMIENTO: <%= @product.establishment.name %></h4>
					<h4>CATEGORIA: <%= Categorie.find(@product.categorie_id).name %></h4>
				</div>
			</row>
			<div class="row">
				<div class="col-md-12">
					<div class="content">
						<table class="table">
							<tr>
								<th class="text-center">INGREDIENTE</th>
								<th class="text-center">CANTIDAD</th>
								<th class="text-center">OPCIONES</th>
							</tr>
							<% @product.product_ingredients.each do |i| %>
							<tr>
								<td><%= i.ingredient.name %></td>
								<td><%= i.quantity %> <%= i.ingredient.unit_of_measurement %></td>
								<td><%= link_to edit_product_ingredient_path(i) do %><span>Editar</span><% end %> - <%= link_to product_ingredient_path(i), method: :delete, data: { confirm: 'Are you sure?' } do %><span>Borrar</span><% end %> </td>
							</tr>
							<% end %>
						</table>
					</div>
				</div>
			</div>
		<div class="row">
			<div class="col-md-12">
				<%= link_to 'Volver a Productos', products_path, :class => 'btn pos_button_blue' %>
				<%= link_to 'Agregar Item A La Receta', new_product_ingredient_path, :class => 'btn pos_button_blue' %>	
			</div>
		</div>	
	</div>
</div>