config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'admin' => 'admins#home'
  get 'kitchen' => 'cook_rooms#home'
  get 'config_user' => 'admins#setup'
  post 'contact' => 'welcome#contact'
  root 'welcome#home'
  get 'products_by_categorie' => 'products#products_by_categorie'
  get 'add_op' => 'orders#add_item'
  get 'remove_op' => 'orders#remove_item'
  get 'generate_invoice' => 'invoices#generate_invoice'
  get 'dashboard' => 'dashboard#home'
  resources :establishments
  resources :ingredients
  resources :inventarios
  resources :products
  resources :product_ingredients
  resources :orders
  resources :invoices

end

app/models/establishment.rb
# == Schema Information
#
# Table name: establishments
#
#  id                  :integer          not null, primary key
#  name                :string
#  address             :string
#  phone               :string
#  tables_number       :integer
#  seats_number        :integer
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  user_id             :integer
#  avatar_file_name    :string
#  avatar_content_type :string
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#

class Establishment < ActiveRecord::Base
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
	validates :name, :address, :phone, :tables_number,:seats_number,:user_id, presence: true
  belongs_to :user
  has_many :establishment_ingredients, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/controllers/establishments_controller.rb
class EstablishmentsController < ApplicationController
	before_action :authenticate_user!
	def new
		@establishment = Establishment.new
	end

	def create
		@establishment = Establishment.new(establishment_params)
		@establishment.user_id = current_user.id
		if @establishment.save
			redirect_to @establishment
		end
	end

	def show
		@establishment = Establishment.find(params[:id])
	end

	def edit
		@establishment = Establishment.find(params[:id])
	end

	def update
		@establishment = Establishment.find(params[:id])
		if @establishment.update(establishment_params)
			redirect_to @establishment			
		end
	end

	def index
		@establishment = current_user.establishment
	end

	def destroy
		@establishment = Establishment.find(params[:id])
		@establishment.destroy
		redirect_to establishments_path
	end

	private
		def establishment_params
  		params.require(:establishment).permit(:name, :address, :phone, :tables_number, :seats_number, :avatar)
		end
end

app/helpers/establishments_helper.rb
module EstablishmentsHelper
end

app/views/establishments/_form.html.erb
<div class="content">
  <%= form_for @establishment do |f| %>
  	<div class="field form-group">
    	<%= f.label :name %><br>
    	<%= f.text_field :name, :class => "form-control" %>
    </div>
    <div class="field form-group">
    	<%= f.label :address %><br>
    	<%= f.text_field :address, :class => "form-control" %>
    </div>
    <div class="field form-group">
    	<%= f.label :phone %><br>
    	<%= f.text_field :phone, :class => "form-control" %>
    </div>
    <div class="field form-group">
    	<%= f.label :numero_de_mesas %><br>
    	<%= f.number_field :tables_number, :class => "form-control" %>
    </div>
    <div class="field form-group">
    	<%= f.label :numero_de_sillas %><br>
    	<%= f.number_field :seats_number, :class => "form-control" %>
    </div>
    <div class="field">
      <%= f.label :imagen %><br>
      <%= f.file_field :avatar, :class => "upload_avatar" %>
    </div>

    <div class="actions form-group text-center">
    	<%= f.submit 'GUARDAR ESTABLECIMIENTO', :class => 'btn pos_button_blue' %>
    </div>
  <% end %>
</div>

app/views/establishments/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h2 class="text-center">EDITAR ESTABLECIMIENTO</h2>
    <%= render "form" %>
  </div>
</div>

app/views/establishments/index.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<table class="table">
			<tr>
				<th>Name</th>
				<th>Direccion</th>
				<th>Telefono</th>
				<th>Numero de mesas</th>
				<th>Numero de sillas</th>
			  <th>Ver - Editar - Borrar</th>
			</tr>
			<tr>
				<td> <%= @establishment.name %> </td>
				<td> <%= @establishment.address %> </td>
				<td> <%= @establishment.phone %> </td>
				<td> <%= @establishment.tables_number %> </td>
				<td> <%= @establishment.seats_number %> </td>
				<td> <%= link_to 'Ver', @establishment %> - <%= link_to 'Editar', edit_establishment_path(@establishment) %> - <%= link_to establishment_path(@establishment), method: :delete, data: { confirm: 'Are you sure?' } do %><span>Borrar</span><% end %></td>
			</tr>
		</table>
		<%= link_to 'Agregar establecimiento', new_establishment_path %>
	</div>
</div>

app/views/establishments/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h2 class="text-center">NUEVO ESTABLECIMIENTO</h2>
    <%= render "form" %>
  </div>
</div>

app/views/establishments/show.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3 text-center">
		<h2 class="text-center">Información de Establecimiento</h2>
			<%= image_tag @establishment.avatar.url(:medium) %>
			<h4>Nombre: <%= @establishment.name %></h4>
			<h4>Direccion: <%= @establishment.address %></h4>
			<h4>Telefono: <%= @establishment.phone %></h4>
			<h4>Numero de mesas: <%= @establishment.tables_number %></h4>
			<h4>Numero de asientos: <%= @establishment.seats_number %></h4>
			<h4>Fecha: <%= @establishment.created_at %></h4>
			<%= link_to 'Regresar', establishments_path, :class => 'btn pos_button_blue' %> 
	</div>
</div>